#### multi dimensional array library

![store data](logo.png)


![store data](applicationOfNumpy.png)


#### NumPy is faster than Lists

#### https://numpy.org/doc/


***
### pip3 install numpy


In [64]:
import numpy as np

In [65]:
# 00000000 00000101  
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [66]:
# 2 dimensional array

b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [67]:
# Get Dimension  [1,2,3]

a.ndim

1

In [68]:
# Get Shape (row col)

b.shape

(2, 3)

In [69]:
# Get Type   [1,2,3]

a.dtype

dtype('int16')

In [70]:
# Get Size  (Bytes)   [1,2,3]

a.itemsize

2

In [71]:
# Get number of elements  [1,2,3]

a.size

3

### Access specific elements, rows, columns, etc

In [116]:
a = np.array([ [1,2,3,4,5,6,7],
               [8,9,10,11,12,13,14]
             ])
print(a)

[2 4 6]


In [73]:
# Get 13 [r, c]

a[1, 5]

13

In [74]:
# Get first row 

a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [75]:
# Get column 3

a[:, 2]

array([ 3, 10])

In [76]:
# [2 4 6] [startindex:endindex:stepsize]

a[0, 1:-1:2]
# a[0, 1:6:2]


array([2, 4, 6])

In [77]:
# change value 

a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### 3-d example

In [78]:
b = np.array([ [ [1,2],[3,4] ],[ [5,6],[7,8] ] ])  
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [79]:
# Get 4

b[0,1,1]

4

In [80]:
# [3 4], [7 8]

b[:,1,:]

array([[3, 4],
       [7, 8]])

###  Different Types of Arrays

In [81]:
# All 0s matrix

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [82]:
# All 1s matrix

np.ones((2,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [83]:
#  other numbers  (shape, num)

np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [84]:
# Any other number (full_like)

np.full_like(a, 5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [85]:
# Random decimal numbers

np.random.rand(3,3)

array([[0.4105154 , 0.58025634, 0.56207939],
       [0.20828515, 0.8208211 , 0.84715355],
       [0.59358749, 0.67485273, 0.1082732 ]])

In [86]:
# Random Integer values  (-2 to 7)

np.random.randint(-2,8, size=(3,3))

array([[ 4,  1,  5],
       [ 7,  5,  0],
       [-1,  4,  4]])

In [87]:
# identity matrix

np.identity(4, dtype='int16')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int16)

#### copy !!!

In [118]:
a = np.array([1,2,3])
# b = a
b = a.copy()
# b = a[:]
b[0] = 100

print(a)

[1 2 3]


### Mathematics

In [89]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [90]:
a + 2

array([3, 4, 5, 6])

In [91]:
a - 2

array([-1,  0,  1,  2])

In [92]:
a * 2

array([2, 4, 6, 8])

In [93]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [94]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [95]:
a ** 2

array([ 1,  4,  9, 16])

In [96]:
# Take the sin

np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [97]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

### Linear Algebra

##### Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)


In [98]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [99]:
# determinant

c = np.identity(3)
np.linalg.det(c)

1.0

##### Statistics

In [100]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
np.min(stats)

1

![axis](axis.png)




In [120]:
# [ [1,2,3],
#   [4,5,6]
# ]

np.max(stats, axis=0)


array([4, 5, 6])

In [103]:
np.sum(stats, axis=1)

array([ 6, 15])

### Reorganizing Arrays

In [104]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print()


after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [105]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [106]:
# Horizontal  stack

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [107]:
filedata = np.genfromtxt('data.txt', delimiter=',')  # cast to float
filedata = filedata.astype('int32')
print(filedata)





[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean and Advanced Indexing

In [108]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [109]:
# > 50 values

filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [110]:
# list of index in numpy (values)

a = np.array([1,2,3,4,5,6,7])
a[[1,2,4]]

array([2, 3, 5])

In [111]:
a = np.array([ [1, 2,  3,  4,  5,  6],
               [8, 9,  10, 11, 12, 13],
              [14, 15, 16, 17, 18, 19],
              [20, 21, 22, 23, 24, 25],
            ])

# 8  9
# 14 15

a[1:3,0:2]



array([[ 8,  9],
       [14, 15]])

In [112]:
# 2
#  10 
#     17 

a[[0,1,2],[1,2,3]]

array([ 2, 10, 17])